### PR TITLE
Change joblisting query

### PR DESCRIPTION
**Pull request by eiriksho**
Change joblisting query

### CODE REVIEW

**Comment by Arashfa0301** [comment]
Could you elaborate with more details what you have done in his pull request :)

**Review by Arashfa0301 — CHANGES_REQUESTED** [review]
Could you elaborate with more details what you have done in his pull request :)

**Comment by eiriksho** [comment]
Used Tox to format the repo. Also needed to change some syntax errors in the tests. Since there has been some updates.

**Review by eiriksho — COMMENTED** [review]
Changed py37 to python3.7. isort added a dash and removed a flag, https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html. Added importlib-metadata in requirements. Lastly changed ugettext_lazy to gettext_lazy.

**Comment by LudvigHz** [comment]
Why are you reformatting the entire repo? I couldn't see any changes to black deps or configs? 
And I ran all tests myself on master and everything looks good. So is there's anything else you changed that required the updates? (It's a bit hard to look through all the files :sweat_smile: )

**Comment by LudvigHz** [comment]
You also need to remove commit [188fbeb](https://github.com/itdagene-ntnu/itdagene/pull/336/commits/188fbebbff2175fac9d1c98bd4805586d4b43d3e) since it looks like you commited an entire venv :upside_down_face:

**Comment by eiriksho** [comment]
Meant more that I used toc to verify the tests. The only change in most of the files was from ugettext-lazy to gettext_lazy. I can remove the commit with the entire venv.

**Review by Arashfa0301 — APPROVED** [review]
Looks good to me :)

**Comment by LudvigHz** [comment]
It's a good idea to squash your commits for PRs like this, where many of the individual commits don't make sense by themselves. eg. https://github.com/itdagene-ntnu/itdagene/pull/336/commits/7c466b6c74b64401b220a28d717c70930d8af6cb and https://github.com/itdagene-ntnu/itdagene/pull/336/commits/ca520d8a5eced10c489969558c8e8aa2c7a746b0 are incorrect (even though they cancel each other out). So they break the history.

**Pull request merged**
